import { JsonValue } from "type-fest";
import { User } from "../user/User";
import { Team } from "../team/Team";
import { Schedule } from "../schedule/Schedule";
import { DestinationCalendar } from "../destinationCalendar/DestinationCalendar";
import { Booking } from "../booking/Booking";
import { Availability } from "../availability/Availability";
import { EventTypeCustomInput } from "../eventTypeCustomInput/EventTypeCustomInput";
import { Webhook } from "../webhook/Webhook";
import { HashedLink } from "../hashedLink/HashedLink";
import { WorkflowsOnEventType } from "../workflowsOnEventType/WorkflowsOnEventType";

export type EventType = {
  id: number;
  title: string;
  slug: string;
  description: string | null;
  position: number;
  locations: JsonValue;
  length: number;
  hidden: boolean;
  users?: Array<User>;
  userId: number | null;
  team?: Team | null;
  eventName: string | null;
  timeZone: string | null;
  periodType?: "UNLIMITED" | "ROLLING" | "RANGE";
  periodStartDate: Date | null;
  periodEndDate: Date | null;
  periodDays: number | null;
  periodCountCalendarDays: boolean | null;
  requiresConfirmation: boolean;
  recurringEvent: JsonValue;
  disableGuests: boolean;
  hideCalendarNotes: boolean;
  minimumBookingNotice: number;
  beforeEventBuffer: number;
  afterEventBuffer: number;
  seatsPerTimeSlot: number | null;
  schedulingType?: "ROUND_ROBIN" | "COLLECTIVE" | null;
  schedule?: Schedule | null;
  price: number;
  currency: string;
  slotInterval: number | null;
  metadata: JsonValue;
  successRedirectUrl: string | null;
  destinationCalendar?: DestinationCalendar | null;
  bookings?: Array<Booking>;
  availability?: Array<Availability>;
  customInputs?: Array<EventTypeCustomInput>;
  webhooks?: Array<Webhook>;
  hashedLink?: HashedLink | null;
  workflows?: Array<WorkflowsOnEventType>;
};
