/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IntFilter } from "../../util/IntFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { EnumWorkflowTrigger } from "./EnumWorkflowTrigger";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { EnumWorkflowTimeUnit } from "./EnumWorkflowTimeUnit";
import { WorkflowStepListRelationFilter } from "../../workflowStep/base/WorkflowStepListRelationFilter";
import { WorkflowsOnEventTypeListRelationFilter } from "../../workflowsOnEventType/base/WorkflowsOnEventTypeListRelationFilter";

@InputType()
class WorkflowWhereInput {
  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  id?: IntFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  name?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumWorkflowTrigger,
  })
  @IsEnum(EnumWorkflowTrigger)
  @IsOptional()
  @Field(() => EnumWorkflowTrigger, {
    nullable: true,
  })
  trigger?: "BEFORE_EVENT" | "EVENT_CANCELLED" | "NEW_EVENT";

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  time?: IntNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumWorkflowTimeUnit,
  })
  @IsEnum(EnumWorkflowTimeUnit)
  @IsOptional()
  @Field(() => EnumWorkflowTimeUnit, {
    nullable: true,
  })
  timeUnit?: "DAY" | "HOUR" | "MINUTE";

  @ApiProperty({
    required: false,
    type: () => WorkflowStepListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WorkflowStepListRelationFilter)
  @IsOptional()
  @Field(() => WorkflowStepListRelationFilter, {
    nullable: true,
  })
  steps?: WorkflowStepListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => WorkflowsOnEventTypeListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WorkflowsOnEventTypeListRelationFilter)
  @IsOptional()
  @Field(() => WorkflowsOnEventTypeListRelationFilter, {
    nullable: true,
  })
  activeOn?: WorkflowsOnEventTypeListRelationFilter;
}

export { WorkflowWhereInput as WorkflowWhereInput };
