/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  SensorType as PrismaSensorType,
  Sensor as PrismaSensor,
} from "@prisma/client";

export class SensorTypeServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SensorTypeCountArgs, "select">
  ): Promise<number> {
    return this.prisma.sensorType.count(args);
  }

  async sensorTypes(
    args: Prisma.SensorTypeFindManyArgs
  ): Promise<PrismaSensorType[]> {
    return this.prisma.sensorType.findMany(args);
  }
  async sensorType(
    args: Prisma.SensorTypeFindUniqueArgs
  ): Promise<PrismaSensorType | null> {
    return this.prisma.sensorType.findUnique(args);
  }
  async createSensorType(
    args: Prisma.SensorTypeCreateArgs
  ): Promise<PrismaSensorType> {
    return this.prisma.sensorType.create(args);
  }
  async updateSensorType(
    args: Prisma.SensorTypeUpdateArgs
  ): Promise<PrismaSensorType> {
    return this.prisma.sensorType.update(args);
  }
  async deleteSensorType(
    args: Prisma.SensorTypeDeleteArgs
  ): Promise<PrismaSensorType> {
    return this.prisma.sensorType.delete(args);
  }

  async findSensors(
    parentId: string,
    args: Prisma.SensorFindManyArgs
  ): Promise<PrismaSensor[]> {
    return this.prisma.sensorType
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .sensors(args);
  }
}
