/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SensorType } from "./SensorType";
import { SensorTypeCountArgs } from "./SensorTypeCountArgs";
import { SensorTypeFindManyArgs } from "./SensorTypeFindManyArgs";
import { SensorTypeFindUniqueArgs } from "./SensorTypeFindUniqueArgs";
import { CreateSensorTypeArgs } from "./CreateSensorTypeArgs";
import { UpdateSensorTypeArgs } from "./UpdateSensorTypeArgs";
import { DeleteSensorTypeArgs } from "./DeleteSensorTypeArgs";
import { SensorFindManyArgs } from "../../sensor/base/SensorFindManyArgs";
import { Sensor } from "../../sensor/base/Sensor";
import { SensorTypeService } from "../sensorType.service";
@graphql.Resolver(() => SensorType)
export class SensorTypeResolverBase {
  constructor(protected readonly service: SensorTypeService) {}

  async _sensorTypesMeta(
    @graphql.Args() args: SensorTypeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SensorType])
  async sensorTypes(
    @graphql.Args() args: SensorTypeFindManyArgs
  ): Promise<SensorType[]> {
    return this.service.sensorTypes(args);
  }

  @graphql.Query(() => SensorType, { nullable: true })
  async sensorType(
    @graphql.Args() args: SensorTypeFindUniqueArgs
  ): Promise<SensorType | null> {
    const result = await this.service.sensorType(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SensorType)
  async createSensorType(
    @graphql.Args() args: CreateSensorTypeArgs
  ): Promise<SensorType> {
    return await this.service.createSensorType({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => SensorType)
  async updateSensorType(
    @graphql.Args() args: UpdateSensorTypeArgs
  ): Promise<SensorType | null> {
    try {
      return await this.service.updateSensorType({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SensorType)
  async deleteSensorType(
    @graphql.Args() args: DeleteSensorTypeArgs
  ): Promise<SensorType | null> {
    try {
      return await this.service.deleteSensorType(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Sensor], { name: "sensors" })
  async findSensors(
    @graphql.Parent() parent: SensorType,
    @graphql.Args() args: SensorFindManyArgs
  ): Promise<Sensor[]> {
    const results = await this.service.findSensors(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
