/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SensorTypeService } from "../sensorType.service";
import { SensorTypeCreateInput } from "./SensorTypeCreateInput";
import { SensorType } from "./SensorType";
import { SensorTypeFindManyArgs } from "./SensorTypeFindManyArgs";
import { SensorTypeWhereUniqueInput } from "./SensorTypeWhereUniqueInput";
import { SensorTypeUpdateInput } from "./SensorTypeUpdateInput";
import { SensorFindManyArgs } from "../../sensor/base/SensorFindManyArgs";
import { Sensor } from "../../sensor/base/Sensor";
import { SensorWhereUniqueInput } from "../../sensor/base/SensorWhereUniqueInput";

export class SensorTypeControllerBase {
  constructor(protected readonly service: SensorTypeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SensorType })
  async createSensorType(
    @common.Body() data: SensorTypeCreateInput
  ): Promise<SensorType> {
    return await this.service.createSensorType({
      data: data,
      select: {
        createdAt: true,
        id: true,
        typeName: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [SensorType] })
  @ApiNestedQuery(SensorTypeFindManyArgs)
  async sensorTypes(@common.Req() request: Request): Promise<SensorType[]> {
    const args = plainToClass(SensorTypeFindManyArgs, request.query);
    return this.service.sensorTypes({
      ...args,
      select: {
        createdAt: true,
        id: true,
        typeName: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SensorType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async sensorType(
    @common.Param() params: SensorTypeWhereUniqueInput
  ): Promise<SensorType | null> {
    const result = await this.service.sensorType({
      where: params,
      select: {
        createdAt: true,
        id: true,
        typeName: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SensorType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSensorType(
    @common.Param() params: SensorTypeWhereUniqueInput,
    @common.Body() data: SensorTypeUpdateInput
  ): Promise<SensorType | null> {
    try {
      return await this.service.updateSensorType({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          typeName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SensorType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSensorType(
    @common.Param() params: SensorTypeWhereUniqueInput
  ): Promise<SensorType | null> {
    try {
      return await this.service.deleteSensorType({
        where: params,
        select: {
          createdAt: true,
          id: true,
          typeName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/sensors")
  @ApiNestedQuery(SensorFindManyArgs)
  async findSensors(
    @common.Req() request: Request,
    @common.Param() params: SensorTypeWhereUniqueInput
  ): Promise<Sensor[]> {
    const query = plainToClass(SensorFindManyArgs, request.query);
    const results = await this.service.findSensors(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,

        sensorType: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/sensors")
  async connectSensors(
    @common.Param() params: SensorTypeWhereUniqueInput,
    @common.Body() body: SensorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sensors: {
        connect: body,
      },
    };
    await this.service.updateSensorType({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/sensors")
  async updateSensors(
    @common.Param() params: SensorTypeWhereUniqueInput,
    @common.Body() body: SensorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sensors: {
        set: body,
      },
    };
    await this.service.updateSensorType({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/sensors")
  async disconnectSensors(
    @common.Param() params: SensorTypeWhereUniqueInput,
    @common.Body() body: SensorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sensors: {
        disconnect: body,
      },
    };
    await this.service.updateSensorType({
      where: params,
      data,
      select: { id: true },
    });
  }
}
