/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumAppModelCategories } from "./EnumAppModelCategories";
import { CredentialUpdateManyWithoutAppModelsInput } from "./CredentialUpdateManyWithoutAppModelsInput";
import { Type } from "class-transformer";
import { WebhookUpdateManyWithoutAppModelsInput } from "./WebhookUpdateManyWithoutAppModelsInput";
import { ApiKeyUpdateManyWithoutAppModelsInput } from "./ApiKeyUpdateManyWithoutAppModelsInput";

@InputType()
class AppModelUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  dirName?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  keys?: InputJsonValue;

  @ApiProperty({
    required: false,
    enum: EnumAppModelCategories,
    isArray: true,
  })
  @IsEnum(EnumAppModelCategories, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumAppModelCategories], {
    nullable: true,
  })
  categories?: Array<
    "calendar" | "messaging" | "other" | "payment" | "video" | "web3"
  >;

  @ApiProperty({
    required: false,
    type: () => CredentialUpdateManyWithoutAppModelsInput,
  })
  @ValidateNested()
  @Type(() => CredentialUpdateManyWithoutAppModelsInput)
  @IsOptional()
  @Field(() => CredentialUpdateManyWithoutAppModelsInput, {
    nullable: true,
  })
  credentials?: CredentialUpdateManyWithoutAppModelsInput;

  @ApiProperty({
    required: false,
    type: () => WebhookUpdateManyWithoutAppModelsInput,
  })
  @ValidateNested()
  @Type(() => WebhookUpdateManyWithoutAppModelsInput)
  @IsOptional()
  @Field(() => WebhookUpdateManyWithoutAppModelsInput, {
    nullable: true,
  })
  webhook?: WebhookUpdateManyWithoutAppModelsInput;

  @ApiProperty({
    required: false,
    type: () => ApiKeyUpdateManyWithoutAppModelsInput,
  })
  @ValidateNested()
  @Type(() => ApiKeyUpdateManyWithoutAppModelsInput)
  @IsOptional()
  @Field(() => ApiKeyUpdateManyWithoutAppModelsInput, {
    nullable: true,
  })
  apiKey?: ApiKeyUpdateManyWithoutAppModelsInput;
}

export { AppModelUpdateInput as AppModelUpdateInput };
