/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Salesperson as PrismaSalesperson,
  Sale as PrismaSale,
} from "@prisma/client";

export class SalespersonServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SalespersonCountArgs, "select">
  ): Promise<number> {
    return this.prisma.salesperson.count(args);
  }

  async salespeople(
    args: Prisma.SalespersonFindManyArgs
  ): Promise<PrismaSalesperson[]> {
    return this.prisma.salesperson.findMany(args);
  }
  async salesperson(
    args: Prisma.SalespersonFindUniqueArgs
  ): Promise<PrismaSalesperson | null> {
    return this.prisma.salesperson.findUnique(args);
  }
  async createSalesperson(
    args: Prisma.SalespersonCreateArgs
  ): Promise<PrismaSalesperson> {
    return this.prisma.salesperson.create(args);
  }
  async updateSalesperson(
    args: Prisma.SalespersonUpdateArgs
  ): Promise<PrismaSalesperson> {
    return this.prisma.salesperson.update(args);
  }
  async deleteSalesperson(
    args: Prisma.SalespersonDeleteArgs
  ): Promise<PrismaSalesperson> {
    return this.prisma.salesperson.delete(args);
  }

  async findSales(
    parentId: string,
    args: Prisma.SaleFindManyArgs
  ): Promise<PrismaSale[]> {
    return this.prisma.salesperson
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .sales(args);
  }
}
