/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Salesperson } from "./Salesperson";
import { SalespersonCountArgs } from "./SalespersonCountArgs";
import { SalespersonFindManyArgs } from "./SalespersonFindManyArgs";
import { SalespersonFindUniqueArgs } from "./SalespersonFindUniqueArgs";
import { CreateSalespersonArgs } from "./CreateSalespersonArgs";
import { UpdateSalespersonArgs } from "./UpdateSalespersonArgs";
import { DeleteSalespersonArgs } from "./DeleteSalespersonArgs";
import { SaleFindManyArgs } from "../../sale/base/SaleFindManyArgs";
import { Sale } from "../../sale/base/Sale";
import { SalespersonService } from "../salesperson.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Salesperson)
export class SalespersonResolverBase {
  constructor(
    protected readonly service: SalespersonService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Salesperson",
    action: "read",
    possession: "any",
  })
  async _salespeopleMeta(
    @graphql.Args() args: SalespersonCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Salesperson])
  @nestAccessControl.UseRoles({
    resource: "Salesperson",
    action: "read",
    possession: "any",
  })
  async salespeople(
    @graphql.Args() args: SalespersonFindManyArgs
  ): Promise<Salesperson[]> {
    return this.service.salespeople(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Salesperson, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Salesperson",
    action: "read",
    possession: "own",
  })
  async salesperson(
    @graphql.Args() args: SalespersonFindUniqueArgs
  ): Promise<Salesperson | null> {
    const result = await this.service.salesperson(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Salesperson)
  @nestAccessControl.UseRoles({
    resource: "Salesperson",
    action: "create",
    possession: "any",
  })
  async createSalesperson(
    @graphql.Args() args: CreateSalespersonArgs
  ): Promise<Salesperson> {
    return await this.service.createSalesperson({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Salesperson)
  @nestAccessControl.UseRoles({
    resource: "Salesperson",
    action: "update",
    possession: "any",
  })
  async updateSalesperson(
    @graphql.Args() args: UpdateSalespersonArgs
  ): Promise<Salesperson | null> {
    try {
      return await this.service.updateSalesperson({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Salesperson)
  @nestAccessControl.UseRoles({
    resource: "Salesperson",
    action: "delete",
    possession: "any",
  })
  async deleteSalesperson(
    @graphql.Args() args: DeleteSalespersonArgs
  ): Promise<Salesperson | null> {
    try {
      return await this.service.deleteSalesperson(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Sale], { name: "sales" })
  @nestAccessControl.UseRoles({
    resource: "Sale",
    action: "read",
    possession: "any",
  })
  async findSales(
    @graphql.Parent() parent: Salesperson,
    @graphql.Args() args: SaleFindManyArgs
  ): Promise<Sale[]> {
    const results = await this.service.findSales(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
