version: "3"
services:
  server:
    build:
      context: ./src
    ports:
      - 5202:8080
    environment:
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_ENVIRONMENT: Development
    restart: on-failure
    profiles:
      - complete
  migrate:
    build:
      context: ./src
    entrypoint: sh
    command: -c './DbMigrationsBundle --connection "$${MIGRATION_CONNECTION}"'
    depends_on:
      db:
        condition: service_healthy
