/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  SensorReading as PrismaSensorReading,
  Sensor as PrismaSensor,
} from "@prisma/client";

export class SensorReadingServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SensorReadingCountArgs, "select">
  ): Promise<number> {
    return this.prisma.sensorReading.count(args);
  }

  async sensorReadings(
    args: Prisma.SensorReadingFindManyArgs
  ): Promise<PrismaSensorReading[]> {
    return this.prisma.sensorReading.findMany(args);
  }
  async sensorReading(
    args: Prisma.SensorReadingFindUniqueArgs
  ): Promise<PrismaSensorReading | null> {
    return this.prisma.sensorReading.findUnique(args);
  }
  async createSensorReading(
    args: Prisma.SensorReadingCreateArgs
  ): Promise<PrismaSensorReading> {
    return this.prisma.sensorReading.create(args);
  }
  async updateSensorReading(
    args: Prisma.SensorReadingUpdateArgs
  ): Promise<PrismaSensorReading> {
    return this.prisma.sensorReading.update(args);
  }
  async deleteSensorReading(
    args: Prisma.SensorReadingDeleteArgs
  ): Promise<PrismaSensorReading> {
    return this.prisma.sensorReading.delete(args);
  }

  async getSensor(parentId: string): Promise<PrismaSensor | null> {
    return this.prisma.sensorReading
      .findUnique({
        where: { id: parentId },
      })
      .sensor();
  }
}
