/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SensorReading } from "./SensorReading";
import { SensorReadingCountArgs } from "./SensorReadingCountArgs";
import { SensorReadingFindManyArgs } from "./SensorReadingFindManyArgs";
import { SensorReadingFindUniqueArgs } from "./SensorReadingFindUniqueArgs";
import { CreateSensorReadingArgs } from "./CreateSensorReadingArgs";
import { UpdateSensorReadingArgs } from "./UpdateSensorReadingArgs";
import { DeleteSensorReadingArgs } from "./DeleteSensorReadingArgs";
import { Sensor } from "../../sensor/base/Sensor";
import { SensorReadingService } from "../sensorReading.service";
@graphql.Resolver(() => SensorReading)
export class SensorReadingResolverBase {
  constructor(protected readonly service: SensorReadingService) {}

  async _sensorReadingsMeta(
    @graphql.Args() args: SensorReadingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SensorReading])
  async sensorReadings(
    @graphql.Args() args: SensorReadingFindManyArgs
  ): Promise<SensorReading[]> {
    return this.service.sensorReadings(args);
  }

  @graphql.Query(() => SensorReading, { nullable: true })
  async sensorReading(
    @graphql.Args() args: SensorReadingFindUniqueArgs
  ): Promise<SensorReading | null> {
    const result = await this.service.sensorReading(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SensorReading)
  async createSensorReading(
    @graphql.Args() args: CreateSensorReadingArgs
  ): Promise<SensorReading> {
    return await this.service.createSensorReading({
      ...args,
      data: {
        ...args.data,

        sensor: args.data.sensor
          ? {
              connect: args.data.sensor,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => SensorReading)
  async updateSensorReading(
    @graphql.Args() args: UpdateSensorReadingArgs
  ): Promise<SensorReading | null> {
    try {
      return await this.service.updateSensorReading({
        ...args,
        data: {
          ...args.data,

          sensor: args.data.sensor
            ? {
                connect: args.data.sensor,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SensorReading)
  async deleteSensorReading(
    @graphql.Args() args: DeleteSensorReadingArgs
  ): Promise<SensorReading | null> {
    try {
      return await this.service.deleteSensorReading(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Sensor, {
    nullable: true,
    name: "sensor",
  })
  async getSensor(
    @graphql.Parent() parent: SensorReading
  ): Promise<Sensor | null> {
    const result = await this.service.getSensor(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
