/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SensorReadingService } from "../sensorReading.service";
import { SensorReadingCreateInput } from "./SensorReadingCreateInput";
import { SensorReading } from "./SensorReading";
import { SensorReadingFindManyArgs } from "./SensorReadingFindManyArgs";
import { SensorReadingWhereUniqueInput } from "./SensorReadingWhereUniqueInput";
import { SensorReadingUpdateInput } from "./SensorReadingUpdateInput";

export class SensorReadingControllerBase {
  constructor(protected readonly service: SensorReadingService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SensorReading })
  async createSensorReading(
    @common.Body() data: SensorReadingCreateInput
  ): Promise<SensorReading> {
    return await this.service.createSensorReading({
      data: {
        ...data,

        sensor: data.sensor
          ? {
              connect: data.sensor,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        sensor: {
          select: {
            id: true,
          },
        },

        timestamp: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [SensorReading] })
  @ApiNestedQuery(SensorReadingFindManyArgs)
  async sensorReadings(
    @common.Req() request: Request
  ): Promise<SensorReading[]> {
    const args = plainToClass(SensorReadingFindManyArgs, request.query);
    return this.service.sensorReadings({
      ...args,
      select: {
        createdAt: true,
        id: true,

        sensor: {
          select: {
            id: true,
          },
        },

        timestamp: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SensorReading })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async sensorReading(
    @common.Param() params: SensorReadingWhereUniqueInput
  ): Promise<SensorReading | null> {
    const result = await this.service.sensorReading({
      where: params,
      select: {
        createdAt: true,
        id: true,

        sensor: {
          select: {
            id: true,
          },
        },

        timestamp: true,
        updatedAt: true,
        value: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SensorReading })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSensorReading(
    @common.Param() params: SensorReadingWhereUniqueInput,
    @common.Body() data: SensorReadingUpdateInput
  ): Promise<SensorReading | null> {
    try {
      return await this.service.updateSensorReading({
        where: params,
        data: {
          ...data,

          sensor: data.sensor
            ? {
                connect: data.sensor,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          sensor: {
            select: {
              id: true,
            },
          },

          timestamp: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SensorReading })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSensorReading(
    @common.Param() params: SensorReadingWhereUniqueInput
  ): Promise<SensorReading | null> {
    try {
      return await this.service.deleteSensorReading({
        where: params,
        select: {
          createdAt: true,
          id: true,

          sensor: {
            select: {
              id: true,
            },
          },

          timestamp: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
